apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-{{ .Values.version }}
  namespace: services
  labels:
    name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0 # Allow all Egress traffic https://github.com/istio/istio/issues/9304
      labels:
        name: {{ .Values.serviceName }}
        version: {{ .Values.version }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      containers:
      - name: {{ .Values.serviceName }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
          - configMapRef:
               name: {{ .Values.serviceName }}-configmap
