apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.serviceName }}
  namespace: services
spec:
  host: {{ .Values.serviceName }}
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary