apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
  namespace: services
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: {{ .Values.serviceName }}
  sessionAffinity: None
  type: ClusterIP